config/routes.rb
Killedbydoozy::Application.routes.draw do
  
  resources :users
  resources :user_sessions
  get "logout" => "user_sessions#destroy", :as => "logout"
  get "login" => "user_sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"

  root :to => 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
	<meta charset="utf-8">
  <meta http-equiv="Content-Type" content="text/html; utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Social Network on Ruby on Rails" />
  <meta name="keywords" content="social network networking ruby on rails" />
  <title><%= @title || SITE_NAME %></title>
  <%= javascript_include_tag 'application' %>
  <%= stylesheet_link_tag 'application' %>
</head>
<body>
	<% if current_user %>
		<%= render :template=>'layouts/sessioned'%>
	<% else %>
	<%= render :template=>'layouts/non_sessioned'%>
	<% end %>
</body>
</html>

app/views/layouts/non_sessioned.html.erb
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Doozy</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href=<%= login_path %>>Sign In</a></li>
        <li><a href=<%= signup_path %>>Join Us?</a></li>
      </ul>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="jumbotron">
    <h1>Doozy</h1>
    <p>Social Network built on Ruby on Rails</p>
    <p>
      <a class="btn btn-lg btn-primary" href=<%= signup_path %> role="button">Join Doozy »</a>
    </p>
  </div>
  <%= render :template=>'/shared/flash.html.erb' %>
  <%= yield %>
</div>

app/views/layouts/sessioned.html.erb
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Doozy</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li><a href="#about">Profile</a></li>
        <li><a href="#contact">Connections</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Messages <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">Conversation</a></li>
            <li><a href="#">New</a></li>
            <li class="divider"></li>
            <li class="dropdown-header">Groups</li>
            <li><a href="#">Conversation</a></li>
            <li><a href="#">New</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Preferences</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">Settings</a></li>
            <li><a href=<%= logout_path %>>Logout</a></li>
          </ul>
        </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>
<div class="container-fluid">
  <div class="jumbotron">
    <h1>Welcome to Doozy</h1>
    <p>Social Network built on Ruby on Rails</p>
  </div>
  <%= render :template=>'/shared/flash.html.erb' %>
  <%= yield %>
</div>